### ISSUE TITLE
Can I take over the namespace?

### ISSUE THREAD

**Issue by gajus** [lamansky/suppress#1]
Hi Lamansky,

Could I take over this namespace on NPM, please?

I would like to re-release [`bluefeather#suppress`](https://github.com/gajus/bluefeather#suppress) as a separate module.

I can make it to work with both Promise and function input so it would remain backwards compatible with what your package is doing at the moment.

If you are happy for me to take over the name, just add me as an NPM admin to the package `npm owner add gajus suppress`.

No worries if you'd prefer to keep the name!

Thank you,

Gajus

**Comment by lamansky** [comment]
Hi Gajus,
I actively maintain my packages, so I'm not giving away the name, but Promise support is a good idea, and I'd certainly welcome a pull request for it.
